version: '3.4'

volumes:
  mysql_data:
      driver: local
services:
  samplewebapi:
    image: ${DOCKER_REGISTRY-}samplewebapi
    container_name: samplewebapi
    build:
      context: ./src
      dockerfile: sampleWebApi/Dockerfile
    depends_on:
        - keycloak
    environment:
      #- ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44328
    ports:
      - "10001:80"
      - "44328:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  sampleangular:
    image: ${DOCKER_REGISTRY-}sampleangular
    container_name: sampleangular
    build:
      context: ./src
      dockerfile: sampleangular/Dockerfile-prod
    depends_on:
        - keycloak
    volumes:
      - '.\sampleangular:/app'
      - '/app/node_modules'
    ports:
      - '4200:80'
    environment:
      - CHOKIDAR_USEPOLLING=true
  mysql:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password

  keycloak:
    image: jboss/keycloak
    container_name: keycloalocalhost
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the MySQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "connectTimeout=30000"
    ports:
      - 8080:8080
    depends_on:
      - mysql
